# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: client CI

on:
  push:
    branches: [ "main" ]



jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Log in to GitHub Container Registry
      run: echo "${{ secrets.CR_PAT }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin
    - run: docker build -t ghcr.io/zeyneperinc/client:latest . -f /home/runner/work/mernexample-client/mernexample-client/Dockerfile
    - run: docker push ghcr.io/zeyneperinc/client:latest

  deploy:
    runs-on: ubuntu-latest
    needs: [ build ]
    steps:
    - run: helm upgrade -i client -n mern /home/runner/work/mernexample-client/mernexample-client/helm/